"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Pencil, ShieldCheck, Sparkles, Trophy } from "lucide-react";
import { AdminModal } from "@/components/admin-modal";
import { AdminUser, PageIntro, Panel, StatusPill, formatDate, formatVc, useAdminUser } from "@/components/admin-shell";
import { apiFetch, ApiError, jsonBody } from "@/lib/api";
import { notifyAdminSuccess } from "@/lib/admin-toast";

type Promotion = { id: string; title: string; slug: string; description: string; status: string; rewardVC: number; startAt: string; endAt: string; _count: { claims: number } };
type VipConfig = { level: string; xpThreshold: number; rewardVC: number };
type Restriction = { user: { id: string; email: string; status: string; profile: { username: string; displayName: string | null } | null }; settings: { dailyWagerLimit: number | null; maxWager: number | null; coolOffUntil: string | null; selfExcludedUntil: string | null; updatedAt: string } };

function Notice({ error, message }: { error: string; message: string }) { return <>{error ? <div className="mb-5 rounded-xl border border-[#643443] bg-[#321b26] px-4 py-3 text-xs text-[#ffadbd]">{error}</div> : null}{message ? <div className="mb-5 rounded-xl border border-[#245a4c] bg-[#12352e] px-4 py-3 text-xs text-[#8af0c4]">{message}</div> : null}</>; }

export function PromotionsAdmin() {
  const [items, setItems] = useState<Promotion[]>([]);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [promotionToUpdate, setPromotionToUpdate] = useState<Promotion | null>(null);
  const load = useCallback(async () => { try { const result = await apiFetch<Promotion[]>("/api/v1/admin/promotions?page=1&pageSize=50"); setItems(result.data); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to load promotions."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiFetch("/api/v1/admin/promotions", { method: "POST", body: jsonBody({ title: form.get("title"), slug: form.get("slug"), description: form.get("description"), startAt: form.get("startAt"), endAt: form.get("endAt"), status: "DRAFT", rewardVC: Number(form.get("rewardVC")), eligibility: {} }) }); setShowCreate(false); const nextMessage = "Promotion created in draft state."; setMessage(nextMessage); notifyAdminSuccess(nextMessage); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to create promotion."); } }
  async function updatePromotion() { if (!promotionToUpdate) return; const item = promotionToUpdate; try { await apiFetch(`/api/v1/admin/promotions/${item.id}`, { method: "PATCH", body: jsonBody({ status: item.status === "ACTIVE" ? "ENDED" : "ACTIVE" }) }); setPromotionToUpdate(null); const nextMessage = `${item.title} updated.`; setMessage(nextMessage); notifyAdminSuccess(nextMessage); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to update promotion."); } }
  return <>
    <PageIntro eyebrow="Growth operations" title="Promotions" description="Create explicit fictional-credit campaigns and manage their lifecycle. Claims are one-time, idempotent, and ledger-backed." action={<button onClick={() => setShowCreate(true)} className="rounded-xl bg-[#83f5c5] px-4 py-3 text-xs font-bold text-[#09120f]"><Sparkles size={14} className="mr-2 inline" />New promotion</button>} />
    <Notice error={error} message={message} />
    <AdminModal description="Draft promotions can be activated after their details are reviewed." onClose={() => setShowCreate(false)} open={showCreate} title="New promotion">
      <form onSubmit={create} className="grid gap-4 md:grid-cols-2">
        <label className="grid gap-2 text-xs font-semibold text-[#8994aa]">Title<input aria-label="Promotion title" name="title" required className="admin-input" /></label>
        <label className="grid gap-2 text-xs font-semibold text-[#8994aa]">Slug<input aria-label="Promotion slug" name="slug" required className="admin-input" /></label>
        <label className="grid gap-2 text-xs font-semibold text-[#8994aa] md:col-span-2">Description<textarea aria-label="Promotion description" name="description" required className="admin-input resize-none" rows={3} /></label>
        <label className="grid gap-2 text-xs font-semibold text-[#8994aa]">Start<input name="startAt" required type="datetime-local" className="admin-input" /></label>
        <label className="grid gap-2 text-xs font-semibold text-[#8994aa]">End<input name="endAt" required type="datetime-local" className="admin-input" /></label>
        <label className="grid gap-2 text-xs font-semibold text-[#8994aa] md:col-span-2">Reward amount<input aria-label="Reward amount" name="rewardVC" required type="number" min="1" className="admin-input" /></label>
        <div className="flex flex-col-reverse gap-3 pt-2 md:col-span-2 sm:flex-row sm:justify-end"><button className="rounded-xl bg-[#83f5c5] px-4 py-3 text-sm font-bold text-[#09120f]" type="submit">Create draft</button></div>
      </form>
    </AdminModal>
    <AdminModal description={promotionToUpdate?.status === "ACTIVE" ? "Ending a promotion stops new claims without removing its history." : "Activating a promotion makes it available according to its configured window."} onClose={() => setPromotionToUpdate(null)} open={Boolean(promotionToUpdate)} title={`${promotionToUpdate?.status === "ACTIVE" ? "End" : "Activate"} ${promotionToUpdate?.title ?? "promotion"}`}>
      <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button className="rounded-xl border border-[#2b3547] px-4 py-3 text-sm font-semibold text-[#b5c0d3] hover:border-[#83f5c5] hover:text-white" onClick={() => setPromotionToUpdate(null)} type="button">Cancel</button><button className="rounded-xl bg-[#83f5c5] px-4 py-3 text-sm font-bold text-[#09120f]" onClick={() => void updatePromotion()} type="button">{promotionToUpdate?.status === "ACTIVE" ? "End promotion" : "Activate promotion"}</button></div>
    </AdminModal>
    <Panel className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="border-b border-[#252d3d] bg-[#151a25] text-[10px] uppercase tracking-[0.16em] text-[#637089]"><tr><th className="px-6 py-4">Promotion</th><th className="px-4 py-4">Window</th><th className="px-4 py-4">Reward</th><th className="px-4 py-4">Claims</th><th className="px-4 py-4">Status</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-[#202837]">{items.map((item) => <tr key={item.id}><td className="px-6 py-4"><p className="text-sm font-semibold text-white">{item.title}</p><p className="mt-1 text-xs text-[#718097]">{item.slug}</p></td><td className="px-4 py-4 text-xs text-[#8994aa]">{formatDate(item.startAt)}<br />to {formatDate(item.endAt)}</td><td className="px-4 py-4 text-xs font-semibold text-[#83f5c5]">{formatVc(item.rewardVC)}</td><td className="px-4 py-4 text-xs text-[#aab4c8]">{item._count.claims}</td><td className="px-4 py-4"><StatusPill value={item.status} /></td><td className="px-6 py-4 text-right"><button onClick={() => setPromotionToUpdate(item)} className="rounded-lg border border-[#2b3547] px-3 py-2 text-xs font-semibold text-[#b5c0d3]">{item.status === "ACTIVE" ? "End" : "Activate"}</button></td></tr>)}</tbody></table>{items.length === 0 ? <div className="p-12 text-center text-sm text-[#718097]">No promotions yet.</div> : null}</div></Panel>
  </>;
}

export function RewardsAdmin() {
  const user = useAdminUser() as AdminUser | null;
  const canEdit = user?.role === "SUPER_ADMIN";
  const [configs, setConfigs] = useState<VipConfig[]>([]);
  const [history, setHistory] = useState<Array<{ id: string; type: string; amountVC: number; createdAt: string; user: { email: string; username: string | null } }>>([]);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const [config, records] = await Promise.all([apiFetch<VipConfig[]>("/api/v1/admin/rewards/config"), apiFetch<typeof history>("/api/v1/admin/rewards/history?page=1&pageSize=25")]); setConfigs(config.data); setHistory(records.data); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to load rewards."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(config: VipConfig) { try { await apiFetch("/api/v1/admin/rewards/config", { method: "PATCH", body: jsonBody(config) }); const nextMessage = `${config.level} configuration updated.`; setMessage(nextMessage); notifyAdminSuccess(nextMessage); await load(); return true; } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to update rewards."); return false; } }
  return <><PageIntro eyebrow="Player incentives" title="Rewards" description="Configure the transparent VIP ladder and inspect immutable reward history. Only Super Admin can change thresholds or reward amounts." /><Notice error={error} message={message} /><Panel className="p-6"><div className="mb-5 flex items-center gap-2"><Trophy size={17} className="text-[#83f5c5]" /><h2 className="text-sm font-semibold text-white">VIP configuration</h2></div><div className="grid gap-3">{configs.map((config) => <RewardRow config={config} canEdit={canEdit} onSave={save} key={config.level} />)}</div></Panel><Panel className="mt-6 overflow-hidden"><div className="border-b border-[#252d3d] px-6 py-5"><h2 className="text-sm font-semibold text-white">Reward history</h2><p className="mt-1 text-xs text-[#718097]">{history.length} recent records</p></div><div className="divide-y divide-[#202837]">{history.map((item) => <div className="flex items-center justify-between gap-4 px-6 py-4" key={item.id}><div><p className="text-sm font-semibold text-white">{item.type.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-[#718097]">{item.user.username ?? item.user.email} · {formatDate(item.createdAt)}</p></div><span className="text-sm font-semibold text-[#83f5c5]">+{formatVc(item.amountVC)}</span></div>)}{history.length === 0 ? <div className="p-10 text-center text-sm text-[#718097]">No reward history.</div> : null}</div></Panel></>;
}

function RewardRow({ config, canEdit, onSave }: { config: VipConfig; canEdit: boolean; onSave: (config: VipConfig) => Promise<boolean> }) {
  const [threshold, setThreshold] = useState(String(config.xpThreshold));
  const [reward, setReward] = useState(String(config.rewardVC));
  const [showEdit, setShowEdit] = useState(false);
  useEffect(() => { setThreshold(String(config.xpThreshold)); setReward(String(config.rewardVC)); }, [config]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const saved = await onSave({ level: config.level, xpThreshold: Number(threshold), rewardVC: Number(reward) }); if (saved) setShowEdit(false); }
  return <><div className="flex items-center justify-between gap-4 rounded-xl border border-[#252d3d] bg-[#0d111a] p-4"><div><p className="text-sm font-semibold text-white">{config.level}</p><p className="mt-1 text-xs text-[#718097]">XP {config.xpThreshold.toLocaleString()} · {formatVc(config.rewardVC)} milestone reward</p></div><button disabled={!canEdit} onClick={() => setShowEdit(true)} className="inline-flex items-center gap-2 rounded-lg border border-[#2b3547] px-3 py-2 text-xs font-semibold text-[#b5c0d3] disabled:opacity-40" type="button"><Pencil size={13} />Edit</button></div><AdminModal description="Update the XP threshold and milestone reward for this level." onClose={() => setShowEdit(false)} open={showEdit} title={`Edit ${config.level} rewards`}><form onSubmit={save} className="grid gap-4"><label className="grid gap-2 text-xs font-semibold text-[#8994aa]">XP threshold<input disabled={!canEdit} value={threshold} onChange={(event) => setThreshold(event.target.value)} type="number" className="admin-input" /></label><label className="grid gap-2 text-xs font-semibold text-[#8994aa]">Reward amount<input disabled={!canEdit} value={reward} onChange={(event) => setReward(event.target.value)} type="number" className="admin-input" /></label><div className="flex flex-col-reverse gap-3 pt-2 sm:flex-row sm:justify-end"><button className="rounded-xl bg-[#83f5c5] px-4 py-3 text-sm font-bold text-[#09120f]" disabled={!canEdit} type="submit">Save changes</button></div></form></AdminModal></>;
}

export function ResponsibleAdmin() {
  const [items, setItems] = useState<Restriction[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { apiFetch<Restriction[]>("/api/v1/admin/responsible-gaming?page=1&pageSize=50").then((result) => setItems(result.data)).catch((reason) => setError(reason instanceof ApiError ? reason.message : "Unable to load restrictions.")); }, []);
  return <><PageIntro eyebrow="Player safety" title="Responsible gaming" description="Read-only inspection of player-configured limits and active pauses. Operators cannot casually override player restrictions from this view." />{error ? <Notice error={error} message="" /> : null}<Panel className="overflow-hidden"><div className="flex items-center gap-2 border-b border-[#252d3d] px-6 py-5"><ShieldCheck size={17} className="text-[#83f5c5]" /><div><h2 className="text-sm font-semibold text-white">Active controls and limits</h2><p className="mt-1 text-xs text-[#718097]">{items.length} players with configured restrictions</p></div></div><div className="divide-y divide-[#202837]">{items.map((item) => <div className="grid gap-4 px-6 py-5 lg:grid-cols-[1.1fr_1fr_auto]" key={item.user.id}><div><p className="text-sm font-semibold text-white">{item.user.profile?.displayName ?? item.user.profile?.username ?? item.user.email}</p><p className="mt-1 text-xs text-[#718097]">{item.user.email}</p></div><div className="flex flex-wrap gap-2 text-xs text-[#aab4c8]">{item.settings.dailyWagerLimit !== null ? <span className="rounded-lg border border-[#2b3547] px-2.5 py-1.5">Daily {formatVc(item.settings.dailyWagerLimit)}</span> : null}{item.settings.maxWager !== null ? <span className="rounded-lg border border-[#2b3547] px-2.5 py-1.5">Max {formatVc(item.settings.maxWager)}</span> : null}{item.settings.coolOffUntil ? <StatusPill value="COOL-OFF" /> : null}{item.settings.selfExcludedUntil ? <StatusPill value="SELF-EXCLUDED" /> : null}</div><p className="text-xs text-[#718097] lg:text-right">Updated {formatDate(item.settings.updatedAt)}</p></div>)}{items.length === 0 ? <div className="p-12 text-center text-sm text-[#718097]">No configured restrictions.</div> : null}</div></Panel></>;
}
